# Generated by Django 4.2.7 on 2025-11-14 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('claims_file', models.FileField(upload_to='uploads/claims/')),
                ('technical_rules_file', models.FileField(blank=True, null=True, upload_to='uploads/rules/')),
                ('medical_rules_file', models.FileField(blank=True, null=True, upload_to='uploads/rules/')),
                ('total_claims', models.IntegerField(default=0)),
                ('processed_claims', models.IntegerField(default=0)),
                ('validated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('encounter_type', models.CharField(max_length=50)),
                ('service_date', models.DateField()),
                ('national_id', models.CharField(max_length=50)),
                ('member_id', models.CharField(max_length=50)),
                ('facility_id', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('diagnosis_codes', models.TextField(help_text='Comma-separated diagnosis codes')),
                ('service_code', models.CharField(max_length=50)),
                ('paid_amount_aed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('not_validated', 'Not Validated')], default='not_validated', max_length=20)),
                ('error_type', models.CharField(choices=[('no_error', 'No Error'), ('medical_error', 'Medical Error'), ('technical_error', 'Technical Error'), ('both', 'Both')], default='no_error', max_length=20)),
                ('error_explanation', models.TextField(blank=True, help_text='Detailed explanation of errors')),
                ('recommended_action', models.TextField(blank=True, help_text='Actionable recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'), models.Index(fields=['error_type'], name='claims_clai_error_t_336f61_idx'), models.Index(fields=['service_code'], name='claims_clai_service_b7fc43_idx')],
            },
        ),
    ]
