# Generated by Django 4.2.7 on 2025-11-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_validated_by_alter_claim_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationjob',
            name='analytics_pipeline_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationjob',
            name='data_validation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationjob',
            name='llm_evaluation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationjob',
            name='metrics_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationjob',
            name='static_rule_evaluation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RefinedClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, max_length=50)),
                ('paid_amount_aed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('not_validated', 'Not Validated')], max_length=20)),
                ('error_type', models.CharField(choices=[('no_error', 'No Error'), ('medical_error', 'Medical Error'), ('technical_error', 'Technical Error'), ('both', 'Both')], max_length=20)),
                ('error_explanation', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('static_rule_validated', models.BooleanField(default=False)),
                ('llm_validated', models.BooleanField(default=False)),
                ('static_rule_errors', models.TextField(blank=True, help_text='Errors from static rule evaluation')),
                ('llm_analysis', models.TextField(blank=True, help_text='LLM-based analysis and recommendations')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refined_claim', to='claims.claim')),
                ('processed_by_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refined_claims', to='claims.validationjob')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['status'], name='claims_refi_status_951e30_idx'), models.Index(fields=['error_type'], name='claims_refi_error_t_c5caa1_idx'), models.Index(fields=['service_code'], name='claims_refi_service_62c53d_idx'), models.Index(fields=['static_rule_validated'], name='claims_refi_static__c5b56b_idx'), models.Index(fields=['llm_validated'], name='claims_refi_llm_val_63595c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('job', 'Per Job')], default='job', max_length=20)),
                ('total_claims', models.IntegerField(default=0)),
                ('validated_count', models.IntegerField(default=0)),
                ('not_validated_count', models.IntegerField(default=0)),
                ('no_error_count', models.IntegerField(default=0)),
                ('medical_error_count', models.IntegerField(default=0)),
                ('technical_error_count', models.IntegerField(default=0)),
                ('both_error_count', models.IntegerField(default=0)),
                ('paid_amount_no_error', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount_medical_error', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount_technical_error', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount_both_error', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('static_rule_processed_count', models.IntegerField(default=0)),
                ('llm_processed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='claims.validationjob')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='claims_metr_period__36bea7_idx'), models.Index(fields=['period_type'], name='claims_metr_period__622139_idx'), models.Index(fields=['job'], name='claims_metr_job_id_c3d7c2_idx')],
                'unique_together': {('period_start', 'period_end', 'period_type', 'job')},
            },
        ),
    ]
