# Generated by Django 4.2.7 on 2025-11-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('technical_rules_file', models.FileField(blank=True, null=True, upload_to='rules/technical/')),
                ('medical_rules_file', models.FileField(blank=True, null=True, upload_to='rules/medical/')),
                ('paid_amount_threshold', models.DecimalField(decimal_places=2, default=250.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=50)),
                ('service_code', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rule_data', models.JSONField(default=dict, help_text='Additional rule configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_rules', to='rules.ruleset')),
            ],
            options={
                'unique_together': {('rule_set', 'rule_type', 'service_code', 'diagnosis_code')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=50)),
                ('service_code', models.CharField(blank=True, max_length=50, null=True)),
                ('encounter_type', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_id', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('rule_data', models.JSONField(default=dict, help_text='Additional rule configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_rules', to='rules.ruleset')),
            ],
            options={
                'unique_together': {('rule_set', 'rule_type', 'service_code', 'encounter_type', 'facility_id', 'diagnosis_code')},
            },
        ),
    ]
